[build]
    publish = "public/"

[functions]
    directory = "functions"

[[redirects]]
    from = "/cors/beat-savior/*"
    to = "https://www.beatsavior.io/api/livescores/player/:splat"
    status = 200
    force = true
    headers = {X-From = "Netlify"}

[[redirects]]
    from = "/cors/score-saber/*"
    to = "https://agitated-ptolemy-7d772c.netlify.app/cors/score-saber/:splat"
    status = 200
    force = true
    headers = {X-From = "Netlify"}

[[redirects]]
    from = "/cors/steamcommunity/*"
    to = "https://steamcommunity.com/:splat"
    status = 200
    force = true
    headers = {X-From = "Netlify"}

[[redirects]]
    from = "/cors/steamapi/*"
    to = "https://api.steampowered.com/:splat"
    status = 200
    force = true
    headers = {X-From = "Netlify"}

[[redirects]]
    from = '/build/*'
    to = '/build/:splat'
    status = 200

[[redirects]]
    from = '/assets/*'
    to = '/assets/:splat'
    status = 200

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
    force = true